version: '3'

services:
  ardapi:
    image: ardwashere/ardapiserver
    container_name: ardapi
    restart: always
    environment:
      - ARDAPI_BASE_URL=/ardapi/v1
      - PORT=3000
    ports:
      - "3000:3000"