version: '3'

services:
  ardapi:
    image: ardwashere/ardapi
    container_name: ardapi
    restart: always
    environment:
      - ARDAPI_BASE_URL=/ardapi/v1
      - ARDAPI_INSTANCE_NAME=default-instance
      - PORT=3000
    ports:
      - "3000:3000"